mqtt:
  enabled: false

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - car

record:
  enabled: false

cameras:

  detskaya_ploshadka_61c1a6ca45:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/detskaya_ploshadka_61c1a6ca45
          input_args: preset-rtsp-restream
          roles:
            - detect

  krylco_d5b65fa148:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/krylco_d5b65fa148
          input_args: preset-rtsp-restream
          roles:
            - detect

  krylco_130:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/krylco_130
          input_args: preset-rtsp-restream
          roles:
            - detect

  dvor_128:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dvor_128
          input_args: preset-rtsp-restream
          roles:
            - detect

  vn_dvor_128:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/vn_dvor_128
          input_args: preset-rtsp-restream
          roles:
            - detect

  torec_126:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/torec_126
          input_args: preset-rtsp-restream
          roles:
            - detect

  etazh_1_130:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/etazh_1_130
          input_args: preset-rtsp-restream
          roles:
            - detect

  sport_ploshadka_126:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/sport_ploshadka_126
          input_args: preset-rtsp-restream
          roles:
            - detect

  parkovka_128:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/parkovka_128
          input_args: preset-rtsp-restream
          roles:
            - detect

  parkovka_128_2:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/parkovka_128_2
          input_args: preset-rtsp-restream
          roles:
            - detect

  parkovka_2_130:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/parkovka_2_130
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173481138:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173481138
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173547486:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173547486
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173588244:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173588244
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173588440:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173588440
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173588496:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173588496
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173588798:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173588798
          input_args: preset-rtsp-restream
          roles:
            - detect

  dsi_173588876:
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/dsi_173588876
          input_args: preset-rtsp-restream
          roles:
            - detect