mqtt:
  enabled: false

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - car

record:
  enabled: false

cameras:

  krylco_130:
    ffmpeg:
      inputs:
        - path: rtsp://host.docker.internal:8554/krylco_130
          input_args: preset-rtsp-restream
          roles:
            - detect