mqtt:
  enabled: false

detect:
  enabled: false
  fps: 5

objects:
  track:
    - person
    - car

record:
  enabled: false

cameras:

  detskaya_ploshadka_61c1a6ca45:
    ffmpeg:
      inputs:
        - path: rtsp://host.docker.internal:8554/detskaya_ploshadka_61c1a6ca45
          input_args: preset-rtsp-restream


  krylco_d5b65fa148:
    ffmpeg:
      inputs:
        - path: rtsp://host.docker.internal:8554/krylco_d5b65fa148
          input_args: preset-rtsp-restream