services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: filebrowser
    restart: unless-stopped

    user: "0:0"

    ports:
      - "5163:80"

    volumes:
      - /:/host
      - ./data:/home/filebrowser/data