services:
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: Europe/Moscow

    ports:
      - "1984:1984/tcp" # Web UI и HTTP API
      - "8554:8554/tcp" # RTSP
      - "8555:8555/tcp" # WebRTC TCP
      - "8555:8555/udp" # WebRTC UDP

    volumes:
      - "./config:/config"