streams:
  detskaya_ploshadka_61c1a6ca45:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.126.detskaya.ploshadka-61c1a6ca45/index.m3u8?token=${DETSKAYA_PLOSHADKA_61C1A6CA45_TOKEN}#video=copy#audio=copy"
  krylco_d5b65fa148:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.126.krylco-d5b65fa148/index.m3u8?token=${KRYLCO_D5B65FA148_TOKEN}#video=copy"
  krylco_130:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.130.krylco-93d31cec82/index.m3u8?token=${KRYLCO_130_TOKEN}#video=copy"
  dvor_128:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.128.dvor-cb8264deb5/index.m3u8?token=${DVOR_128_TOKEN}#video=copy"
  vn_dvor_128:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.128.vn.dvor-badd9d0ea2/index.m3u8?token=${VN_DVOR_128_TOKEN}#video=copy"
  torec_126:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.126.torec-4b8720e1a6/index.m3u8?token=${TOREC_126_TOKEN}#video=copy"
  etazh_1_130:
    - "ffmpeg:https://vs4.newbwc.ru/osvobozhdeniya.130.1.etazh-2a08469b95/index.m3u8?token=${ETAZH_1_130_TOKEN}#video=copy"
  sport_ploshadka_126:
    - "ffmpeg:https://vs2.newbwc.ru/osvobozhdeniya.126.sport.ploshadka-f97d1fbce7/index.m3u8?token=${SPORT_PLOSHADKA_126_TOKEN}#video=copy"