ffmpeg:
  dsi: '-user_agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/150.0.0.0 Safari/537.36" -headers "Origin: https://video.dsi.ru\r\nReferer: https://video.dsi.ru/\r\n" -i {input}'

streams:
  detskaya_ploshadka_61c1a6ca45:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.126.detskaya.ploshadka-61c1a6ca45/index.m3u8?token=${DETSKAYA_PLOSHADKA_61C1A6CA45_TOKEN}#video=copy#audio=copy"
  krylco_d5b65fa148:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.126.krylco-d5b65fa148/index.m3u8?token=${KRYLCO_D5B65FA148_TOKEN}#video=copy"
  krylco_130:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.130.krylco-93d31cec82/index.m3u8?token=${KRYLCO_130_TOKEN}#video=copy"
  dvor_128:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.128.dvor-cb8264deb5/index.m3u8?token=${DVOR_128_TOKEN}#video=copy"
  vn_dvor_128:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.128.vn.dvor-badd9d0ea2/index.m3u8?token=${VN_DVOR_128_TOKEN}#video=copy"
  torec_126:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.126.torec-4b8720e1a6/index.m3u8?token=${TOREC_126_TOKEN}#video=copy"
  etazh_1_130:
    - "ffmpeg:https://vs4.newbwc.ru/osvobozhdeniya.130.1.etazh-2a08469b95/index.m3u8?token=${ETAZH_1_130_TOKEN}#video=copy"
  sport_ploshadka_126:
    - "ffmpeg:https://vs2.newbwc.ru/osvobozhdeniya.126.sport.ploshadka-f97d1fbce7/index.m3u8?token=${SPORT_PLOSHADKA_126_TOKEN}#video=copy"
  parkovka_128:
    - "ffmpeg:https://vs6.newbwc.ru/osvobozhdeniya.128.parkovka-9566f5570b/index.m3u8?token=${PARKOVKA_128_TOKEN}#video=copy"
  parkovka_128_2:
    - "ffmpeg:https://vs3.newbwc.ru/osvobozhdeniya.128.parkovka-be228782f0/index.m3u8?token=${PARKOVKA_128_2_TOKEN}#video=copy"
  parkovka_2_130:
    - "ffmpeg:https://vs2.newbwc.ru/osvobozhdeniya.130.parkovka.2-338fad0443/index.m3u8?token=${PARKOVKA_2_130_TOKEN}#video=copy"
  dsi_173481138:
    - "ffmpeg:${DSI_173481138_URL}#input=dsi#video=copy"
  dsi_173547486:
    - "ffmpeg:${DSI_173547486_URL}#input=dsi#video=copy"
  dsi_173588244:
    - "ffmpeg:${DSI_173588244_URL}#input=dsi#video=copy"
  dsi_173588440:
    - "ffmpeg:${DSI_173588440_URL}#input=dsi#video=copy"
  dsi_173588496:
    - "ffmpeg:${DSI_173588496_URL}#input=dsi#video=copy"
  dsi_173588798:
    - "ffmpeg:${DSI_173588798_URL}#input=dsi#video=copy"