# ОПТИМИЗАЦИЯ ПРОИЗВОДИТЕЛЬНОСТИ
max_filedescriptors 16384
workers 4

# КЭШИРОВАНИЕ
cache_dir ufs /var/spool/squid 5000 16 256
cache_mem 512 MB
maximum_object_size 2048 MB

# ТАЙМАУТЫ
forward_timeout 300 seconds
connect_timeout 60 seconds
read_timeout 300 seconds
request_timeout 300 seconds
persistent_request_timeout 300 seconds